spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: bookstore_user
    password: bookstore_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true